facebook:
  client:
    clientId: 276923603251050
    clientSecret: 69a2f836d8c3d8f24fdebb3d56e965e2
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    redirectUri: localhost:8081
  resource:
    userInfoUri: https://graph.facebook.com/me

github:
  client:
    clientId: 235aadab9bd43bbbe5b5
    clientSecret: ad5d4e7eff5e4665a4cf1d4ac84ce5685836af6d
    accessTokenUri: https://github.com/login/oauth/access_token
    tokenName: oauth_token
    authenticationScheme: query
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

spring.main.allow-bean-definition-overriding: true
